#!/bin/sh

##################################################
# HLL wrapper script.
# Put this script together with hll.pl in a
# directory that is listed in $PATH, eg. ~/bin.
##################################################

if [ ! -d "$PCLP_PATH" ]; then
    echo 'Please define $PCLP_PATH' >&2
    exit 1
fi

MSG_TXT_PATH="$PCLP_PATH/msg.txt"

if [ ! -f "$MSG_TXT_PATH" ]; then
    echo "Cannot find $MSG_TXT_PATH" >&2
    exit 1
fi

hll.pl "$MSG_TXT_PATH" "$@"
